# VaultStaticSecret - sync database credentials from Vault
# Generated K8s Secret: anomaly-detector-secrets
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: ap-explanation-static-secret
  namespace: upcite
spec:
  vaultAuthRef: vault-auth-upcite
  mount: kvv2
  type: kv-v2
  path: upcite/anomaly-detector
  destination:
    create: true
    name: anomaly-detector-secrets
